### ISSUE TITLE
roslaunch　error

### ISSUE THREAD

**Issue by ChenyangRan** [TolgaOk/ur_gym#2]
Hi, when I use the roslaunch ur10_gym.launch. some errors happens:

![Screenshot from 2019-09-28 14-25-56](https://user-images.githubusercontent.com/29306735/65812612-ecf48700-e1fb-11e9-9e0f-867dc8e4c49a.png)

Ubuntu16.04
Ros-kinetic

What should I do to run it correctly?

**Comment by saralopez7** [comment]
I have the same problem in Ubuntu 18.04 and ros melodic. 

Do you remember how yo fixed it?
